### ISSUE TITLE
common 包在哪呢？ 可以提供在工程里面吗 

### ISSUE THREAD

**Issue by bj-huozhe** [likedan130/mongo-file#1]
<parent>
        <artifactId>loctek-common</artifactId>
        <groupId>com.loctek.common</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

**Comment by likedan130** [comment]
这是pom文件修改残留，已经修复，只需要依赖springboot即可

**Comment by likedan130** [comment]
> loctek-common com.loctek.common 1.0-SNAPSHOT

这是pom文件修改残留，已经修复，只需要依赖springboot即可
